name: final_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  http: ^0.13.4
  redux: ^5.0.0
  redux_epics: ^0.15.0
  flutter_redux: ^0.8.2
  freezed_annotation: ^1.0.0
  json_annotation: ^4.4.0

dependency_overrides:
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.0.2
  json_serializable: ^6.1.1
  build_runner: ^2.1.5

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  fonts:
    - family: Parisienne
      fonts:
        - asset: assets/Parisienne.ttf
    - family: Tangerine
      fonts:
        - asset: assets/Tangerine.ttf
